name: Build Quarto Book

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("tidyverse", "tidyquant", "quantmod", "PerformanceAnalytics", "timetk", "lubridate", "scales", "ggthemes", "kableExtra"))'

    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Render Quarto book
      run: quarto render

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_book