project:
  type: book
  output-dir: _book

book:
  title: "Ethical econometriX"
  subtitle: "Advancing the Art and Science of Financial Analytics with Econometrics, Bayesian Methods, and Machine Learning"
  author: "Barry Quinn"
  cover-image: "images/stable_diffusion_cover.png"
  date: '`r Sys.Date()`'
  chapters:
    - index.qmd
    - part: "Core Concepts"
      chapters:
        - primer.qmd
        - tools.qmd
        - returns.qmd
        - time_series.qmd
        - bayesian_methods.qmd
        - ml.qmd
    - part: "Advanced Material"
      chapters: 
        - multilevel.qmd
        - causal.qmd
        - colliderbias.qmd
    - references.qmd
  appendices: 
    - resources.qmd
    - solutions.qmd
    - academic-integrity.qmd
  page-footer:
    left: |
      Don't Fence Me In by Barry Quinn
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>
  site-url: https://quinfer.github.io/encing
  repo-url: https://github.com/quinfer/encing
  repo-branch: main
  repo-actions: [edit, issue]

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto
  warning: false
  message: false
  echo: true
  eval: true

packages:
  - tidyverse
  - tidyquant
  - quantmod
  - PerformanceAnalytics
  - timetk
  - lubridate
  - scales
  - ggthemes
  - kableExtra