name: Publish Quarto Book

on:
  push:
    branches: main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'

      - name: Set Cran Mirror
        run: echo 'options(repos = c(CRAN = "https://cran.r-project.org"))' > ~/.Rprofile
 
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev libfreetype6-dev libpng-dev libtiff5-dev
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev

      - name: Install R Dependencies
        run: |
            options(repos = c(CRAN = "https://cran.r-project.org"))
            if (!requireNamespace("renv", quietly=TRUE)) install.packages("renv")
        shell: Rscript {0}

      - name: Install Additional R Packages
        run: |
          options(repos = c(CRAN = "https://cran.r-project.org"))
          install.packages(c(
            'tidyverse', 'tidyquant', 'quantmod', 'PerformanceAnalytics', 
            'timetk', 'lubridate', 'scales', 'ggthemes', 'kableExtra',
            'janitor', 'rmarkdown', 'knitr', 'bookdown', 'htmltools',
            'remotes'
          ))
          remotes::install_github("quinfer/tsfe")
        shell: Rscript {0}
        env:
          GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}

      - name: Render Book
        run: |
          quarto render
          ls -la _book

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_book'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 